#!/usr/bin/env bash
# install.sh — symlink dots into place. Idempotent; backs up anything real.
#
#   --no-tmux      leave ~/.tmux.conf alone
#   --no-terminal  skip the kitty background image
#
# --no-tmux exists for hosts whose tmux config is owned by something else and is
# purpose-built for that host — kali-deploy-remote writes a headless SSH config
# (auto-attach, multi-window) that is a better fit there than this repo's. Note
# that without it the symlink would also mean any tool doing `cat > ~/.tmux.conf`
# writes straight into this repo.
#
# --no-terminal skips the owl. It is already a no-op on a box with no kitty --
# every headless box, which is most of them -- so the flag is for a box that has
# kitty and does not want it.
set -euo pipefail

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP="$HOME/.dotfiles-backup/$(date +%Y%m%d-%H%M%S)"

NO_TMUX=0
NO_TERMINAL=0
while [ $# -gt 0 ]; do
    case "$1" in
        --no-tmux) NO_TMUX=1 ;;
        --no-terminal) NO_TERMINAL=1 ;;
        -h|--help) sed -n '2,15p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) echo "install.sh: unknown option '$1'" >&2; exit 1 ;;
    esac
    shift
done

link() {
    local src="$1" dst="$2"
    if [ -L "$dst" ] && [ "$(readlink -f "$dst")" = "$(readlink -f "$src")" ]; then
        echo "ok    $dst"
        return
    fi
    if [ -e "$dst" ] || [ -L "$dst" ]; then
        mkdir -p "$BACKUP"
        mv "$dst" "$BACKUP/"
        echo "backup $dst -> $BACKUP/"
    fi
    mkdir -p "$(dirname "$dst")"
    ln -s "$src" "$dst"
    echo "link  $dst -> $src"
}

# ~/.bash_aliases is the hook Kali's stock .bashrc already sources.
link "$DOTFILES/shell/bash_aliases" "$HOME/.bash_aliases"
if [ "$NO_TMUX" -eq 1 ]; then
    echo "skip  ~/.tmux.conf (--no-tmux)"
else
    link "$DOTFILES/tmux/tmux.conf" "$HOME/.tmux.conf"
fi

# zsh has no stock drop-in Kali auto-sources, so append a guarded hook to
# ~/.zshrc (non-destructive — Kali keeps its prompt/plugins; we add ours after).
hook_zsh() {
    local rc="$HOME/.zshrc" marker="# >>> red-team dotfiles >>>"
    [ -f "$rc" ] || { echo "skip  no ~/.zshrc (not using zsh?)"; return; }
    if grep -qF "$marker" "$rc"; then
        echo "ok    ~/.zshrc hook already present"
        return
    fi
    mkdir -p "$BACKUP"; cp "$rc" "$BACKUP/.zshrc"
    cat >> "$rc" <<EOF

$marker
[ -r "$DOTFILES/shell/zshrc" ] && source "$DOTFILES/shell/zshrc"
# <<< red-team dotfiles <<<
EOF
    echo "hook  appended red-team block to ~/.zshrc (backup in $BACKUP/)"
}
hook_zsh

# The owl, for boxes that have a terminal capable of drawing one.
#
# kitty is the only target: it is what the deploy scripts install on a desktop
# Kali box, and it takes a background image from its own config file, so this
# stays inside Linux. A headless box has no kitty and skips the whole thing.
#
# The image is generated rather than shipped. terminal/ stores an alpha mask and
# a tint script, so the finished picture is per-machine and lives outside the
# repo -- writing it into the checkout would leave install.sh dirtying git.
hook_kitty() {
    local share="${XDG_DATA_HOME:-$HOME/.local/share}/dots"
    local kdir="${XDG_CONFIG_HOME:-$HOME/.config}/kitty"
    local kconf="$kdir/kitty.conf"
    local marker="# >>> red-team dotfiles: owl >>>"
    local tint="${DOTS_OWL_TINT:-slate}"

    command -v kitty >/dev/null 2>&1 || { echo "skip  owl (no kitty on this box)"; return; }
    python3 -c 'import PIL' 2>/dev/null || {
        echo "skip  owl (needs Pillow: apt install python3-pil)"
        return
    }

    mkdir -p "$share"
    local png="$share/owl-$tint.png"
    python3 "$DOTFILES/terminal/mkowl.py" --tint "$tint" -o "$png" >/dev/null || {
        echo "warn  owl image could not be generated -- leaving kitty alone" >&2
        return
    }

    # kitty does not expand ~ or $HOME in background_image, so the path has to be
    # written out absolute at install time. That is why this fragment is
    # generated here instead of being a tracked file we could just symlink.
    cat > "$share/kitty-owl.conf" <<KITTYCONF
# Generated by dots/install.sh. Edits are overwritten on the next run.
# Retune with: DOTS_OWL_TINT=ash ./install.sh   (bone, ash, slate, char, or #hex)
background_image        $png
background_image_layout cscaled
background_image_linear yes
background_tint         0.75
background_tint_gaps    0
KITTYCONF

    mkdir -p "$kdir"
    [ -f "$kconf" ] || : > "$kconf"
    if grep -qF "$marker" "$kconf"; then
        echo "ok    kitty owl include already present ($tint)"
        return
    fi
    mkdir -p "$BACKUP"; cp "$kconf" "$BACKUP/kitty.conf" 2>/dev/null || true
    cat >> "$kconf" <<KITTYHOOK

$marker
include $share/kitty-owl.conf
# <<< red-team dotfiles: owl <<<
KITTYHOOK
    echo "hook  owl ($tint) -> $kconf"
}
[ "$NO_TERMINAL" -eq 1 ] && echo "skip  owl (--no-terminal)" || hook_kitty

# Make bin scripts executable
chmod +x "$DOTFILES"/bin/* 2>/dev/null || true

# Ops dirs
mkdir -p "$HOME/ops/tmux-logs"

echo
echo "done. open a new shell or run:  source ~/.bashrc"
[ -d "$BACKUP" ] && echo "originals saved in: $BACKUP"
