#!/usr/bin/env bash
# install.sh — symlink dots into place. Idempotent; backs up anything real.
#
#   --no-tmux      leave ~/.tmux.conf alone
#   --no-terminal  skip the kitty background image and the wallpaper
#
# --no-tmux exists for hosts whose tmux config is owned by something else and is
# purpose-built for that host — kali-deploy-remote writes a headless SSH config
# (auto-attach, multi-window) that is a better fit there than this repo's. Note
# that without it the symlink would also mean any tool doing `cat > ~/.tmux.conf`
# writes straight into this repo.
#
# --no-terminal skips the owl and the desktop wallpaper. Both are already no-ops
# on a box that lacks the thing they hook into -- kitty for the owl, feh for the
# wallpaper, neither of which is on a headless box -- so the flag is for a box
# that has them and does not want the look.
set -euo pipefail

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP="$HOME/.dotfiles-backup/$(date +%Y%m%d-%H%M%S)"

NO_TMUX=0
NO_TERMINAL=0
while [ $# -gt 0 ]; do
    case "$1" in
        --no-tmux) NO_TMUX=1 ;;
        --no-terminal) NO_TERMINAL=1 ;;
        -h|--help) sed -n '2,15p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) echo "install.sh: unknown option '$1'" >&2; exit 1 ;;
    esac
    shift
done

link() {
    local src="$1" dst="$2"
    if [ -L "$dst" ] && [ "$(readlink -f "$dst")" = "$(readlink -f "$src")" ]; then
        echo "ok    $dst"
        return
    fi
    if [ -e "$dst" ] || [ -L "$dst" ]; then
        mkdir -p "$BACKUP"
        mv "$dst" "$BACKUP/"
        echo "backup $dst -> $BACKUP/"
    fi
    mkdir -p "$(dirname "$dst")"
    ln -s "$src" "$dst"
    echo "link  $dst -> $src"
}

# ~/.bash_aliases is the hook Kali's stock .bashrc already sources.
link "$DOTFILES/shell/bash_aliases" "$HOME/.bash_aliases"
if [ "$NO_TMUX" -eq 1 ]; then
    echo "skip  ~/.tmux.conf (--no-tmux)"
else
    link "$DOTFILES/tmux/tmux.conf" "$HOME/.tmux.conf"
fi

# zsh has no stock drop-in Kali auto-sources, so append a guarded hook to
# ~/.zshrc (non-destructive — Kali keeps its prompt/plugins; we add ours after).
hook_zsh() {
    local rc="$HOME/.zshrc" marker="# >>> red-team dotfiles >>>"
    [ -f "$rc" ] || { echo "skip  no ~/.zshrc (not using zsh?)"; return; }
    if grep -qF "$marker" "$rc"; then
        echo "ok    ~/.zshrc hook already present"
        return
    fi
    mkdir -p "$BACKUP"; cp "$rc" "$BACKUP/.zshrc"
    cat >> "$rc" <<EOF

$marker
[ -r "$DOTFILES/shell/zshrc" ] && source "$DOTFILES/shell/zshrc"
# <<< red-team dotfiles <<<
EOF
    echo "hook  appended red-team block to ~/.zshrc (backup in $BACKUP/)"
}
hook_zsh

# The owl, for boxes that have a terminal capable of drawing one.
#
# kitty is the only target: it is what the deploy scripts install on a desktop
# Kali box, and it takes a background image from its own config file, so this
# stays inside Linux. A headless box has no kitty and skips the whole thing.
#
# The image is generated rather than shipped. terminal/ stores an alpha mask and
# a tint script, so the finished picture is per-machine and lives outside the
# repo -- writing it into the checkout would leave install.sh dirtying git.
hook_kitty() {
    local share="${XDG_DATA_HOME:-$HOME/.local/share}/dots"
    local kdir="${XDG_CONFIG_HOME:-$HOME/.config}/kitty"
    local kconf="$kdir/kitty.conf"
    local marker="# >>> red-team dotfiles: owl >>>"
    local tint="${DOTS_OWL_TINT:-slate}"

    command -v kitty >/dev/null 2>&1 || { echo "skip  owl (no kitty on this box)"; return; }
    python3 -c 'import PIL' 2>/dev/null || {
        echo "skip  owl (needs Pillow: apt install python3-pil)"
        return
    }

    mkdir -p "$share"
    # A hex tint would put a '#' in the filename. kitty parses that fine, but it
    # is needless friction everywhere else -- shell quoting, copy-paste, any tool
    # that treats it as a fragment -- so the name is sanitised, not the value.
    local slug="${tint//[^A-Za-z0-9._-]/}"
    local png="$share/owl-$slug.png"
    python3 "$DOTFILES/terminal/mkowl.py" --tint "$tint" -o "$png" >/dev/null || {
        echo "warn  owl image could not be generated -- leaving kitty alone" >&2
        return
    }

    # kitty does not expand ~ or $HOME in background_image, so the path has to be
    # written out absolute at install time. That is why this fragment is
    # generated here instead of being a tracked file we could just symlink.
    cat > "$share/kitty-owl.conf" <<KITTYCONF
# Generated by dots/install.sh. Edits are overwritten on the next run.
# Retune with: DOTS_OWL_TINT=ash ./install.sh   (bone, ash, slate, char, or #hex)
background_image        $png
background_image_layout cscaled
background_image_linear yes
background_tint         0.75
background_tint_gaps    0
KITTYCONF

    mkdir -p "$kdir"
    [ -f "$kconf" ] || : > "$kconf"
    if grep -qF "$marker" "$kconf"; then
        echo "ok    kitty owl include already present ($tint)"
        return
    fi
    mkdir -p "$BACKUP"; cp "$kconf" "$BACKUP/kitty.conf" 2>/dev/null || true
    cat >> "$kconf" <<KITTYHOOK

$marker
include $share/kitty-owl.conf
# <<< red-team dotfiles: owl <<<
KITTYHOOK
    echo "hook  owl ($tint) -> $kconf"
}
[ "$NO_TERMINAL" -eq 1 ] && echo "skip  owl (--no-terminal)" || hook_kitty

# The lock and login screen image. The owl, not the desktop wallpaper: the
# wallpaper is the Ghost in the Shell card and stays that way, and the two
# screens you are shut out behind get the bird instead.
#
# A finished picture, unlike the terminal owl next door. That one is a bare mask
# kitty composites over its own background; lightdm and i3lock both want an
# opaque image at screen proportions, so this one is composited here -- owl
# centred on #282828, which is the ground every other surface already uses.
#
# Not gated on kitty, unlike hook_kitty: nothing about a lock screen needs a
# terminal to exist. Only Pillow, and generated at 2560x1440 so it scales down
# to a 1080p panel cleanly rather than up.
#
# It stops at generating the file. Publishing it somewhere the greeter can read
# it needs root, and the greeter runs as the lightdm user which cannot see into
# this home at all -- that copy is kali-deploy-physical's job, in the same
# division of labour as everything else here.
hook_lockimage() {
    local share="${XDG_DATA_HOME:-$HOME/.local/share}/dots"
    local tint="${DOTS_OWL_TINT:-slate}"
    local png="$share/owl-lock.png"

    python3 -c 'import PIL' 2>/dev/null || {
        echo "skip  lock image (needs Pillow: apt install python3-pil)"
        return
    }

    # --fit 0.7 --y 0.34. The greeter's login box sits dead centre and cannot be
    # moved without an anchor argument that is easy to get wrong, so the bird
    # moves instead: lifted to 34% of the height, the box lands on the branch
    # below it and the face stays clear. Shrinking alone does not do it --
    # --fit scales around the same centre, so the box still covers the face.
    mkdir -p "$share"
    if python3 "$DOTFILES/terminal/mkowl.py" --tint "$tint" --canvas 2560x1440 \
            --fit 0.7 --y 0.34 -o "$png" >/dev/null; then
        echo "hook  lock image ($tint) -> $png"
    else
        echo "warn  lock image could not be generated" >&2
    fi
}
[ "$NO_TERMINAL" -eq 1 ] && echo "skip  lock image (--no-terminal)" || hook_lockimage

# The desktop wallpaper. Lives here rather than in the deploy script for the same
# reason the owl does: this repo owns what the box looks like, and the deploy
# scripts own what is installed on it. They already split that way -- the deploy
# installs kitty and writes kitty.conf, this appends the owl to it; the deploy
# installs feh and has i3 run ~/.fehbg at session start, this decides what
# ~/.fehbg points at.
#
# ~/.fehbg is written directly rather than by running `feh --bg-fill`, because
# feh needs a live X display to set a background and install.sh is routinely run
# from a TTY, over SSH, or mid-deploy with no session at all. The file is just a
# shell script that calls feh; i3 executes it when the session starts, and feh
# rewrites it whenever you set a different background later -- so this is the
# same handoff without the requirement to be inside X when it happens.
#
# Only written when absent: it is the default, and a re-run must not overrule a
# background you picked yourself.
#
# The feh check makes this self-disabling on every headless box, the same way the
# kitty check does for the owl -- feh is in kali-deploy-physical's package list
# and not in the remote's, so nothing here needs to know which box it is on.
hook_wallpaper() {
    local img="$DOTFILES/terminal/wallpaper.png"
    local fehbg="$HOME/.fehbg"

    command -v feh >/dev/null 2>&1 || { echo "skip  wallpaper (no feh on this box)"; return; }
    [ -f "$img" ] || { echo "skip  wallpaper (terminal/wallpaper.png missing)"; return; }
    if [ -e "$fehbg" ]; then
        echo "ok    ~/.fehbg already set (leaving your background alone)"
        return
    fi

    cat > "$fehbg" <<FEHBG
#!/bin/sh
# Written by dots/install.sh. i3 runs this at session start.
# Change the background with:  feh --bg-fill /path/to/image
# feh rewrites this file when you do, so there is nothing here to edit.
feh --no-fehbg --bg-fill '$img'
FEHBG
    chmod 755 "$fehbg"
    echo "hook  wallpaper -> $fehbg"
}
[ "$NO_TERMINAL" -eq 1 ] && echo "skip  wallpaper (--no-terminal)" || hook_wallpaper

# Make bin scripts executable
chmod +x "$DOTFILES"/bin/* 2>/dev/null || true

# Ops dirs
mkdir -p "$HOME/ops/tmux-logs"

echo
echo "done. open a new shell or run:  source ~/.bashrc"
# An `if`, not `[ -d ... ] && echo`. $BACKUP carries this run's timestamp and is
# only created when something actually had to be saved, so on a re-run with
# nothing to back up that AND-list returns 1 -- and being the last statement, it
# made the whole script exit 1. A clean re-run has always done this; it stayed
# invisible until tools/install-test.sh started checking the exit code, and even
# then it only showed when the two runs straddled a second boundary, because
# otherwise the first run's directory sits at the second run's identical path.
# An `if` with a false condition returns 0.
if [ -d "$BACKUP" ]; then
    echo "originals saved in: $BACKUP"
fi
